/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudoemail.types.inputs

import com.sudoplatform.sudoemail.SudoEmailClient
import com.sudoplatform.sudoemail.types.ScheduledDraftMessageState

sealed interface ScheduledDraftMessageStateFilterInput

/**
 * @property equal [ScheduledDraftMessageState] Return only results that match the given state.
 */
data class EqualStateFilter(
    val equal: ScheduledDraftMessageState,
) : ScheduledDraftMessageStateFilterInput

/**
 * @property oneOf [List<ScheduledDraftMessageState>] Return only results that match one of the given states.
 */
data class OneOfStateFilter(
    val oneOf: List<ScheduledDraftMessageState>,
) : ScheduledDraftMessageStateFilterInput

/**
 * @property notEqual [ScheduledDraftMessageState] Return only results that do not match the given state.
 */
data class NotEqualStateFilter(
    val notEqual: ScheduledDraftMessageState,
) : ScheduledDraftMessageStateFilterInput

/**
 * @property notOneOf [List<ScheduledDraftMessageState>] Return only results that do not match any of the given states.
 */
data class NotOneOfStateFilter(
    val notOneOf: List<ScheduledDraftMessageState>,
) : ScheduledDraftMessageStateFilterInput

/**
 * @property state [ScheduledDraftMessageStateFilterInput] Used to filter results based on `state` property
 */
data class ScheduledDraftMessageFilterInput(
    val state: ScheduledDraftMessageStateFilterInput? = null,
)

/**
 * Input object containing email address id and other parameters used to list scheduled draft messages for
 * an email address.
 *
 * @property emailAddressId [String] The identifier of the email address to list for.
 * @property limit [Int] Number of records to return. If omitted, the limit defaults to 10.
 * @property nextToken [String] A token generated by a previous call to [SudoEmailClient.listScheduledDraftMessagesForEmailAddressId].
 * This is to allow for pagination. This value should be generated from a previous
 * pagination call, otherwise it will throw an exception. The same arguments should be
 * supplied to this method if using a previously generated [nextToken].
 * @property filter [ScheduledDraftMessageFilterInput] Properties used to filter the results.
 */
data class ListScheduledDraftMessagesForEmailAddressIdInput(
    val emailAddressId: String,
    val limit: Int? = null,
    val nextToken: String? = null,
    val filter: ScheduledDraftMessageFilterInput? = null,
)
