/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudoemail.types.inputs

import com.sudoplatform.sudoemail.SudoEmailClient
import com.sudoplatform.sudoemail.types.EmailMaskRealAddressType
import com.sudoplatform.sudoemail.types.EmailMaskStatus

sealed interface EmailMaskStatusFilterInput

/**
 * @property equal [EmailMaskStatus] Return only results that match the given state.
 */
data class EqualStatusFilter(
    val equal: EmailMaskStatus,
) : EmailMaskStatusFilterInput

/**
 * @property oneOf [List<EmailMaskStatus>] Return only results that match one of the given states.
 */
data class OneOfStatusFilter(
    val oneOf: List<EmailMaskStatus>,
) : EmailMaskStatusFilterInput

/**
 * @property notEqual [EmailMaskStatus] Return only results that do not match the given state.
 */
data class NotEqualStatusFilter(
    val notEqual: EmailMaskStatus,
) : EmailMaskStatusFilterInput

/**
 * @property notOneOf [List<EmailMaskStatus>] Return only results that do not match any of the given states.
 */
data class NotOneOfStatusFilter(
    val notOneOf: List<EmailMaskStatus>,
) : EmailMaskStatusFilterInput

sealed interface EmailMaskRealAddressTypeFilterInput

data class EqualRealAddressTypeFilter(
    val equal: EmailMaskRealAddressType,
) : EmailMaskRealAddressTypeFilterInput

data class OneOfRealAddressTypeFilter(
    val oneOf: List<EmailMaskRealAddressType>,
) : EmailMaskRealAddressTypeFilterInput

data class NotEqualRealAddressTypeFilter(
    val notEqual: EmailMaskRealAddressType,
) : EmailMaskRealAddressTypeFilterInput

data class NotOneOfRealAddressTypeFilter(
    val notOneOf: List<EmailMaskRealAddressType>,
) : EmailMaskRealAddressTypeFilterInput

/**
 * @property status [EmailMaskStatusFilterInput] Used to filter results based on `status` property
 */
data class EmailMaskFilterInput(
    val status: EmailMaskStatusFilterInput? = null,
    val realAddressType: EmailMaskRealAddressTypeFilterInput? = null,
)

/**
 * Input object containing email address id and other parameters used to list scheduled draft messages for
 * an email address.
 *
 * @property limit [Int] Number of records to return. If omitted, the limit defaults to 10.
 * @property nextToken [String] A token generated by a previous call to [SudoEmailClient.listScheduledDraftMessagesForEmailAddressId].
 * This is to allow for pagination. This value should be generated from a previous
 * pagination call, otherwise it will throw an exception. The same arguments should be
 * supplied to this method if using a previously generated [nextToken].
 * @property filter [ScheduledDraftMessageFilterInput] Properties used to filter the results.
 */
data class ListEmailMasksForOwnerInput(
    val limit: Int? = null,
    val nextToken: String? = null,
    val filter: EmailMaskFilterInput? = null,
)
