/*
 * Copyright © 2025 Anonyome Labs, Inc. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.sudoplatform.sudoemail.types.inputs

/**
 * Input object containing information required to list draft email message metadata
 * for a specific email address with pagination support.
 *
 * @property emailAddressId [String] The identifier of the email address associated with the draft messages.
 * @property limit [Int] Maximum number of draft messages to return. Defaults to 10 if not specified.
 * @property nextToken [String] A token generated by a previous call to allow for pagination.
 */
data class ListDraftEmailMessageMetadataForEmailAddressIdInput(
    val emailAddressId: String,
    val limit: Int? = 10,
    val nextToken: String? = null,
)
